### ISSUE TITLE
"patternlab:serve" creates duplicate asset instances

### ISSUE THREAD

**Issue by ryanaltvater** [pattern-lab/edition-node-gulp#116] opened 2017-12-19 16:22 UTC
After running `gulp patternlab:version`, I am using Pattern Lab Node- Gulp Edition `v3.0.0-alpha.5` on `Mac` as-is right out of the box without any modifications.

##### Expected Behavior
Run `gulp patternlab:serve` and I should only see a single instance of each asset folder (CSS, fonts, images, js).

##### Actual Behavior
Run `gulp patternlab:serve` and I am seeing duplicate instances of each asset folder.

![screen shot 2017-12-19 at 11 16 26 am](https://user-images.githubusercontent.com/1336787/34167047-9e44855c-e4ae-11e7-9ab6-d1792e65fec8.png)

##### Steps to Reproduce
1. Run `gulp patternlab:serve`
2. Check inside each asset folder in the `public` folder

**Comment by bmuenzenmeyer** [comment] 2017-12-19 16:58
Thanks for this report (and the others!). Keep them coming. 

In this case, this is a duplicate of https://github.com/pattern-lab/patternlab-node/issues/762 and therefore will close it.

Rest assured, I intend to shore up this functionality.

**Closed as completed by bmuenzenmeyer** 2017-12-19 16:58 UTC
Labels: duplicate
