### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by ryanaltvater** [pattern-lab/edition-node-gulp#117] opened 2017-12-19 16:25 UTC
After running `gulp patternlab:version`, I am using Pattern Lab Node- Gulp Edition `v3.0.0-alpha.5` on `Mac` as-is right out of the box without any modifications.

##### Expected Behavior
Run `gulp patternlab:serve` without errors

##### Actual Behavior
Run `gulp patternlab:serve` with errors

![screen shot 2017-12-18 at 4 58 25 pm](https://user-images.githubusercontent.com/1336787/34130178-de589c86-e414-11e7-85c8-67fd495dd770.png)

##### Steps to Reproduce
1. Run `gulp patternlab:serve`
2. Open the console tab in Chrome DevTools for errors

**Comment by andeersg** [comment] 2018-01-07 10:43
I have noticed the same with a completely fresh download from this repo.

**Comment by nrooban** [comment] 2018-01-08 03:44
![image](https://user-images.githubusercontent.com/4565888/34658339-1d9d6f98-f469-11e7-9917-6659cb9cb2b1.png)

I too getting this. also in windows

**Comment by bmuenzenmeyer** [comment] 2018-01-08 13:18
I think I have this resolved with the latest code on `dev` of `patternlab-node` but I have yet to released it.

In the meantime, I'd check out the latest **stable** Edition found here: https://github.com/pattern-lab/edition-node-gulp/releases

**Comment by zookee1** [comment] 2018-01-11 13:41
Hej @bmuenzenmeyer,
we are facing the same issues. Is there an approx. release date for 3.0 or the alpha-6?

Cheers

**Comment by bmuenzenmeyer** [comment] 2018-01-11 16:52
@zookee1 It's done when https://github.com/pattern-lab/patternlab-node/milestone/22 is done.

I'll ship alpha.6 when it's more stable. If I shipped it now we'd be swapping out the issue mostly reported here (different than the OP's issue, actually) with issues about pattern parameters. The [async work](https://github.com/pattern-lab/patternlab-node/issues/707) has been a massive disruption in the codebase. I'm trying to be as transparent as possible with these releases - keep the reports coming. If you find something that is already reported, a 👍 is more valuable to me than a "me too" comment.

**Comment by zookee1** [comment] 2018-01-12 07:39
@bmuenzenmeyer thanks for the clarification! :)

**Comment by bmuenzenmeyer** [comment] 2018-01-16 14:20
Please upgrade `@pattern-lab/patternlab-node` to `3.0.0-alpha.6` and report back findings

**Comment by samsmithnz** [comment] 2018-01-20 13:27
Also seeing this, as well as a favicon.ico issue, when generating and setting up in IIS (on Windows)
![postreleaseerrors](https://user-images.githubusercontent.com/8389039/35183916-b45a0490-fdbb-11e7-93ba-fde40dadf1c5.png)

**Comment by hhsl** [comment] 2018-01-22 14:10
Patternlab 3.0.0.-alpha.6 works like a charm, upgrading was as easy as cleaning up and upgrading our build scripts to Gulp4. Thanks!

Unfortunately the styleguide is making some [problems]( https://github.com/pattern-lab/styleguidekit-assets-default/blob/b5e64ef1f02ae04859fc2503dc077e5451c84a5f/dist/index.html#L377), basically I can confirm @samsmithnz report. The index of the styleguide tries to import a bower_component which is not inside of the dist folder. Another problem is "Uncaught ReferenceError: config is not defined at index.html", referencing this [line](https://github.com/pattern-lab/styleguidekit-assets-default/blob/b5e64ef1f02ae04859fc2503dc077e5451c84a5f/dist/index.html#L349), for example when clicking View All of a molecule.

Currently we have `"@pattern-lab/styleguidekit-assets-default": "^4.0.0-alpha.2"` and `"@pattern-lab/patternlab-node": "^3.0.0-alpha.7"` installed as our project dependencies.

**Comment by mearleycf** [comment] 2018-02-15 18:46
I'm still seeing this issue in v3.0.0-alpha.7.

**Comment by bmuenzenmeyer** [comment] 2018-02-16 20:35
Trying to get a handle on this issue which is covering a lot of ground...

- [X] [object Promise][object Promise][object Promise] - upgrade to latest [@pattern-lab/patternlab-node alpha](https://www.npmjs.com/package/@pattern-lab/patternlab-node)
- [X] classList.min.js (according to git, removed in`@pattern-lab/styleguidekit-assets-default@4.0.0-alpha.2`. also double checked as part of latest [@pattern-lab/styleguidekit-assets-default](https://www.npmjs.com/package/@pattern-lab/styleguidekit-assets-default) 
- [X] Favicon - open a separate issue if this is still a thing
- [X] `"Uncaught ReferenceError: config is not defined at index.html", referencing this line, for example when clicking View All of a molecule.` - open a separate issue if this is still a thing
- [ ] `Uncaught SyntaxError: Unexpected token <` what this issue pertains to. Troubleshooting continues

**Comment by bmuenzenmeyer** [comment] 2018-02-16 21:01
Please try again with https://github.com/pattern-lab/edition-node-gulp/releases/tag/v2.0.0-alpha.2

**Comment by samsmithnz** [comment] 2018-02-16 22:32
There is a lot going on here, I had to jump over to the WebPack version to find a solution that worked. The WebPack version seems to be stable, with more recent releases as a bonus. Note that the favicon issue seems to be a problem over there too, (but is easy to fix).

**Comment by hhsl** [comment] 2018-02-19 08:16
@samsmithnz the webpack edition is using patternlab-node-2, not 3.

@bmuenzenmeyer most of the bugs seem to be solved by the alpha releases, thanks! 

As far as I know only these problems occured :
- clicking on "View All" of an Atom Folder results in TypeError: document.getElementById(...) is null in 
patternlab-viewer.js:1363
- Pseudopatterns still have all the same data.

Should I open a new issue for this, especially for the patternlab-viewer.js of the styleguidekit-assets-default?

**Comment by samsmithnz** [comment] 2018-02-19 11:38
@hhsl fair comment, but if I'm using Github properly (and it's likely I'm not), the last stable 2x release for the Gulp version was in 2016. https://github.com/pattern-lab/edition-node-gulp/releases/tag/v1.3.4. Did I miss something? I'm new here, and I'm finding the versioning challenging to get straight.

**Comment by hhsl** [comment] 2018-02-20 08:36
You're absolutely right @samsmithnz, it is confusing. I just tried to clarify that the webpack-edition is running with different versions than the problems described in this issue.

**Comment by bmuenzenmeyer** [comment] 2018-02-22 14:34
@samsmithnz 

> fair comment, but if I'm using Github properly (and it's likely I'm not), the last stable 2x release for the Gulp version was in 2016. https://github.com/pattern-lab/edition-node-gulp/releases/tag/v1.3.4. Did I miss something? I'm new here, and I'm finding the versioning challenging to get straight.

You're using Github just fine. 👍 

Pattern Lab Editions are pre-packaged sets of the different modules that make up the entire working product. We call this [the ecosystem](http://patternlab.io/docs/advanced-ecosystem-overview.html).

The reason this repo can appear stale is because it's actually quite stable - with most of the work being done within the [patternlab-node core](https://github.com/pattern-lab/patternlab-node). I hope that helps clear things up a bit.

Please continue to use Pattern Lab and report your findings. If you have time to help, even better!

**Comment by pay-dro** [comment] 2018-03-05 01:44
After upgrading to the latest versions of @pattern-lab packages, issues continue. These are the versions in use:
```
@pattern-lab/edition-node-gulp 2.0.0-alpha.5
@pattern-lab/patternengine-node-mustache 2.0.0-alpha.2
@pattern-lab/patternlab-node 3.0.0-alpha.8
@pattern-lab/styleguidekit-assets-default 4.0.0-alpha.3
@pattern-lab/styleguidekit-mustache-default 4.0.0-alpha.1
```
Console error on load:
![image](https://user-images.githubusercontent.com/10779000/36953351-e48400a0-1fce-11e8-9212-d392bd5d26dd.png)

When clicking View All link from any pattern sub-type in the nav:
![image](https://user-images.githubusercontent.com/10779000/36953391-30fffa56-1fcf-11e8-804c-e5654661c5e0.png)

Glad to provide further details.

**Closed as completed** 2018-03-21 12:34 UTC

**Comment by Seanom** [comment] 2018-04-24 20:10
Sorry I realised that this issue should be over here https://github.com/pattern-lab/patternlab-node/issues/835

I'm still getting this using 3.0.0-alpha.11

![image](https://user-images.githubusercontent.com/331839/39211462-8e28440c-4803-11e8-8aca-3d14be69dbaa.png)

I'm using the starterkit-mustache-demo just in case that makes a difference?
