### ISSUE TITLE
Bower component not generated in windows

### ISSUE THREAD

**Issue by arianjinx** [pattern-lab/edition-node-gulp#85] opened 2016-10-21 10:17 UTC
I am using Pattern Lab Node- Gulp Edition `v1.3.2` on `Windows`.
##### Expected Behavior

Bower component in `/styleguide` should be generated
##### Actual Behavior

Not generated and resulting 404 on home
##### Steps to Reproduce

Run all just like documentation tells in Windows 7

**Comment by iammikecohen** [comment] 2016-10-26 21:07
I also had this issue. The problem appears to be in the pl-copy:styleguide task. Use Gulp debug to see what the task is grabbing and where it is moving those files. For me changing the task to the following worked:

```
// Styleguide Copy everything but css
gulp.task('pl-copy:styleguide', function(){
  return gulp.src('**/!(*.css)', {cwd: paths().source.styleguide})
    .pipe(gulp.dest(path.resolve(paths().public.root + '/styleguide')))
    .pipe(browserSync.stream());
});
```

**Comment by bmuenzenmeyer** [comment] 2016-10-27 15:44
I haven't run PL Node on Windows 7 in a long long time, but can confirm that this is working on Windows 10 against a copy of this repo.

![image](https://cloud.githubusercontent.com/assets/298435/19774326/4a612262-9c32-11e6-9f01-5f215ff2529f.png)

What version of node are you running? `node - v`

**Comment by bmuenzenmeyer** [comment] 2016-11-02 04:45
Update 1: I tested this tonight and am getting a ton of 404's on the client - which is not expected.

Investigating.

Update 2: This entire task seems to not be working all of a sudden:

```
gulp.task('pl-copy:styleguide', function(){
  return gulp.src(path.resolve(paths().source.styleguide), '**/!(*.css)')
    .pipe(gulp.dest(path.resolve(paths().public.root)))
    .pipe(browserSync.stream());
});
```

In addition to bower_components, fonts and js directories are likewise not copied.

Update 3: https://github.com/gulpjs/gulp/issues/1842

**Comment by bmuenzenmeyer** [comment] 2016-11-02 05:56
@arianjinx a fix for this is now on the `dev` branch. will go out with next release

**Comment by arianjinx** [comment] 2016-11-03 04:56
Hello thank you @bmuenzenmeyer sorry i just read the update, nice 😆 .
I managed to have some temporary fix by changing styleguide path to this (adding cwd).
`return gulp.src(path.resolve(paths().source.styleguide, 'styleguide/**/!(*.css)'), { cwd: path.resolve(paths().source.styleguide, 'styleguide') })`
Although it breaks gulp and needs to restart sometimes, but it's okay.

**Comment by spuz** [comment] 2016-11-04 10:00
Sorry to say this issue is still unresolved for me. I am running Windows 10, Node v6.8.1, npm v3.10.9, gulp-cli 1.2.2, and gulp v4.0.0-alpha.2

Steps to reproduce:
1. clone repo
2. run `npm install` 
3. run `gulp pl-copy:styleguide`

This results in an empty folder `dist` in `public/styleguide/`.
If I run `gulp pl-copy:styleguide-css` the folder structure looks like this `public/styleguide/css/dist/` whereas `dist` is empty too.

**Closed as completed** 2016-11-06 03:10 UTC
Labels: bug

**Comment by bmuenzenmeyer** [comment] 2016-11-06 03:16
https://github.com/pattern-lab/edition-node-gulp/releases/tag/v1.3.4 should resolve this - would appreciate independent verification!

**Comment by spuz** [comment] 2016-11-07 09:47
I hereby confirm: it is working as expected. Thank you very much!
